### ISSUE TITLE
Integration tests and sample crash the compiler on non-JVM targets

### ISSUE THREAD

**Issue by ZacSweers** [ZacSweers/metro#18]
Currently, non-jvm targets fail with "IrValueParameterSymbolImpl is already bound" exceptions

```
e: java.lang.IllegalStateException: IrValueParameterSymbolImpl is already bound. Signature: null.
Owner: VALUE_PARAMETER INSTANCE_RECEIVER name:<this> type:<uninitialized parent>.$$LatticeGraph
    at org.jetbrains.kotlin.ir.symbols.impl.IrSymbolBase.bind(IrSymbolImpl.kt:67)
    at org.jetbrains.kotlin.ir.declarations.impl.IrValueParameterImpl.<init>(IrValueParameterImpl.kt:48)
    at org.jetbrains.kotlin.ir.declarations.IrFactory.createValueParameter(IrFactory.kt:407)
    at org.jetbrains.kotlin.backend.common.serialization.IrDeclarationDeserializer.deserializeIrValueParameter
    (IrDeclarationDeserializer.kt:298)
    at org.jetbrains.kotlin.backend.common.serialization.IrDeclarationDeserializer.deserializeIrValueParameter
    $default(IrDeclarationDeserializer.kt:294)
```

I don't really know why duplicate classes would be generated just for these targets but not others? Happens with macOS, JS, WASM, etc.

**Comment by ZacSweers** [comment]
actually I wonder if it's related to https://youtrack.jetbrains.com/issue/KT-53992 and https://youtrack.jetbrains.com/issue/KT-73612/Support-deserialisation-of-IrExpressionBody
